# Generated by Django 2.1.3 on 2018-11-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20181109_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='good_cnt',
            field=models.IntegerField(default=0, verbose_name='good_cnt'),
        ),
    ]
